### use balance
POST http://localhost:8080/transactions/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100000
}

### use balance2
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10
}