### use balance
POST http://localhost:8080/transactions/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100000
}

### use balance2
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10
}

### get transaction
GET http://localhost:8080/transactions/c704f8aa6ee84235b79e62c70e0f0a82